name: Docker Images

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: docker-elasticsearch-analysis
            image_tag: 8.5.3
            verify_command: "elasticsearch --version"
  
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and load docker images
        uses: docker/build-push-action@v3
        with:
          load: true
          context: "{{defaultContext}}"
          tags: ${{ matrix.image_name }}:${{ matrix.image_tag }}

      - name: Verify docker images built success
        run: docker run --rm --entrypoint "/bin/bash" ${{ matrix.image_name }}:${{ matrix.image_tag }} -c "${{ matrix.verify_command }} || exit 1"

      - name: Build and push docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}"
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ matrix.image_tag }}, ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image_name }}:latest

